version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    env_file: .env
    volumes:
      - zero2prod_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  test-postgres:
    image: postgres:latest
    container_name: test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test-pass
      POSTGRES_DB: test
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    env_file: .env
    ports:
      - "8099:8099"

volumes:
  zero2prod_data:

